In [1]:
%tensorflow_version 2.x

In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [3]:
a = tf.Variable(0, name= 'input')
b = tf.constant(1)

for i in range(3):
  a = a + b
  print(a)
print(a.shape)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
()


In [ ]:
f = tf.constant(3.142, tf.float32)
i = tf.cast(f, dtype = tf.int32)
print(f.dtype)
print(i.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


Rank - number of dimensions involved in tensor

In [8]:
tensor1 = tf.ones([2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor1, [3,2])

In [9]:
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [11]:
tf.rank(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
tf.rank(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
rank4tensor = tf.ones([3,2,4,5], dtype = tf.int32)

In [6]:
print(rank4tensor)

tf.Tensor(
[[[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]], shape=(3, 2, 4, 5), dtype=int32)


In [7]:
tf.rank(rank4tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [13]:
print(rank4tensor.dtype)
print(rank4tensor.ndim)
print(rank4tensor.shape, rank4tensor.shape[0], rank4tensor.shape[-1])
tf.size(rank4tensor).numpy()

<dtype: 'int32'>
4
(3, 2, 4, 5) 3 5


120

Placeholders - can take input from user at runtime

In [ ]:
%tensorflow_version 1.x
import tensorflow.compat.v1 as tf

placeholder_ex = tf.placeholder(tf.int32, shape = (1, 2, 3))
print(placeholder_ex)

Tensor("Placeholder:0", shape=(1, 2, 3), dtype=int32)


In [ ]:
%tensorflow_version 2.x
import tensorflow as tf

string = tf.Variable("My name is string", tf.string)
number = tf.Variable(32, tf.int16)
floating = tf.Variable(31.567, tf.float64)

In [ ]:
print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'My name is string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=31.567>


Indexing

Slicing

Tensorflow operators

# Lab 2/3

In [14]:
# Vectorization

import numpy as np
a = np.array([1,2,3,4])
print(a)
b = np.random.rand(5)
print(b)


[1 2 3 4]
[0.55820265 0.29311571 0.84256035 0.78303661 0.13377756]


Broadcasting

# Lab 4 - Binary Classification with Logistic Regression

In [ ]:
%tensorflow_version 2.x

In [ ]:
import tensorflow as tf
print(tf.version)
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os
from os import getcwd

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
#check present working directory
!pwd

/content


In [ ]:
#Mounting Google Drive
from google.colab